/* lexdef.h - lexer definitions

   generated by genlex 0.1.0-alpha  3 Oct 2022  5:12

   from lua.lex 0.1.0  3 Oct 2022  5:14 lua
   options: code yes  tokens yes
 */
static const char specnam[] = "lua.lex";

static const char lexinfo[] = "lua.lex 0.1.0   3 Oct 2022  5:14 lua  code yes  tokens yes";

#define Cclen 4

#define Kwhshmsk 63
#define Kwhshbit  6

#define x t99_count

static const ub1 kwhsh[64] = {
  x  ,x  ,x  ,x  ,x  ,x  ,2  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  , // ...... elseif.........
  19 ,x  ,4  ,x  ,x  ,x  ,3  ,1  ,13 ,20 ,x  ,x  ,x  ,7  ,x  ,x  , //  break. false... end else repeat continue... goto..
  x  ,18 ,x  ,6  ,x  ,x  ,16 ,10 ,x  ,5  ,14 ,x  ,x  ,x  ,x  ,x  , // . while. function.. true local. for return.....
  x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,11 ,15 ,17 ,12 ,x  ,x   // .......... nil then until not..
  };
#undef x

#define Kwhshshift(h) h >> 5
static const ub1 hikwlen = 8;
static const ub1 mikwlen = 5;
static const ub1 kwhshmap[21] = { 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,19 }; // token to Token

#define Bltcnt 139
#define Blthshmsk 1023
#define Blthshbit  10

#define x B99_count

static const ub1 blthsh[1024] = {
  x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,85 ,111,x  ,x  ,x  ,x  ,x  ,x  , // ........ huge file......
  x  ,73 ,x  ,x  ,x  ,77 ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  , // . sort... asin..........
  x  ,x  ,75 ,x  ,x  ,x  ,109,10 ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  , // .. abs... tmpfile next........
  x  ,x  ,x  ,x  ,130,x  ,x  ,x  ,134,x  ,x  ,74 ,91 ,x  ,x  ,x  , // .... getupvalue... setupvalue.. math modf...
  88 ,x  ,41 ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,13 , //  maxinteger. path............ print
  x  ,78 ,x  ,x  ,x  ,x  ,61 ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,81 , // . atan.... unpack........ deg
  x  ,x  ,x  ,5  ,3  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,22 ,x  , // ... error collectgarbage......... type.
  x  ,x  ,x  ,x  ,x  ,37 ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,38 , // ..... config......... cpath
  119,x  ,124,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  , //  exit. tmpname.............
  x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  , // ................
  20 ,x  ,x  ,x  ,x  ,x  ,x  ,132,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  , //  tonumber...... sethook........
  21 ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  , //  tostring...............
  x  ,x  ,102,72 ,122,31 ,48 ,x  ,x  ,x  ,x  ,25 ,2  ,x  ,x  ,79 , // .. flush remove setlocale running dump.... xpcall assert.. ceil
  x  ,34 ,x  ,x  ,x  ,x  ,x  ,x  ,19 ,x  ,x  ,x  ,x  ,x  ,x  ,x  , // . yield...... setmetatable.......
  x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,32 ,x  ,x  ,x  ,x  , // ........... status....
  x  ,x  ,x  ,x  ,x  ,x  ,x  ,138,44 ,89 ,x  ,x  ,x  ,x  ,82 ,x  , // ....... upvaluejoin searchpath min.... exp.
  x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,103,x  ,113,x  ,x  ,x  ,x  ,x  , // ........ input. setvbuf.....
  x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  , // ................
  x  ,x  ,x  ,x  ,x  ,x  ,69 ,x  ,x  ,45 ,9  ,x  ,x  ,x  ,x  ,x  , // ...... concat.. string loadfile.....
  x  ,x  ,x  ,x  ,x  ,70 ,x  ,x  ,x  ,x  ,126,x  ,x  ,x  ,x  ,x  , // ..... insert.... gethook.....
  x  ,x  ,x  ,96 ,x  ,x  ,x  ,x  ,x  ,94 ,x  ,x  ,55 ,x  ,x  ,x  , // ... sin..... random.. match...
  x  ,x  ,x  ,x  ,x  ,x  ,52 ,x  ,x  ,x  ,x  ,x  ,x  ,33 ,x  ,57 , // ...... gsub...... wrap. packsize
  x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,6  ,x  ,108,x  ,x  ,x  ,x  ,x  , // ........ getmetatable. read.....
  84 ,x  ,x  ,x  ,x  ,60 ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,83 ,x  , //  fmod.... sub........ flor.
  x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  , // ................
  x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,125,x  ,x  ,28 ,x  , // ........... debug.. create.
  x  ,x  ,x  ,x  ,x  ,x  ,x  ,14 ,x  ,x  ,x  ,x  ,x  ,104,x  ,137, // ....... rawequalk..... lines. upvalueid
  x  ,x  ,x  ,120,105,x  ,x  ,x  ,17 ,x  ,x  ,x  ,x  ,x  ,x  ,x  , // ... getenv open... rawset.......
  x  ,x  ,x  ,x  ,x  ,53 ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,87 ,x  ,x  , // ..... len....... max..
  110,x  ,x  ,x  ,x  ,x  ,x  ,29 ,80 ,x  ,x  ,x  ,x  ,x  ,x  ,x  , //  write...... isyieldable cos.......
  x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  , // ................
  36 ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  , //  package...............
  x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,54 ,x  ,x  ,x  ,x  ,x  , // .......... lower.....
  x  ,x  ,x  ,x  ,24 ,115,x  ,x  ,x  ,x  ,67 ,x  ,71 ,x  ,x  ,x  , // .... warn clock.... offset. move...
  30 ,x  ,x  ,x  ,x  ,65 ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,50 , //  resume.... codes......... format
  x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,112,x  , // .............. seek.
  x  ,x  ,x  ,x  ,8  ,x  ,x  ,x  ,46 ,x  ,x  ,x  ,x  ,x  ,x  ,x  , // .... load... byte.......
  x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,118,x  ,x  ,x  ,x  ,x  ,x  ,x  , // ........ execute.......
  x  ,x  ,x  ,x  ,x  ,x  ,100,x  ,x  ,106,x  ,x  ,x  ,x  ,x  ,x  , // ...... ult.. output......
  x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  , // ................
  x  ,x  ,62 ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  , // .. upper.............
  x  ,x  ,x  ,x  ,x  ,128,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  , // ..... getlocal..........
  x  ,x  ,131,x  ,11 ,x  ,x  ,x  ,47 ,x  ,x  ,x  ,x  ,98 ,x  ,x  , // .. getuservale. pairs... char.... tan..
  x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,116,x  ,x  ,x  ,x  , // ........... date....
  x  ,x  ,x  ,x  ,x  ,x  ,x  ,135,x  ,123,x  ,x  ,x  ,x  ,x  ,x  , // ....... setuservalue. time......
  x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,12 ,x  ,7  ,x  ,x  ,x  ,99 , // ......... pcall. ipairs... tointeger
  x  ,66 ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,129,x  , // . codepoint............ getregistry.
  133,x  ,x  ,x  ,x  ,x  ,63 ,x  ,x  ,x  ,x  ,49 ,x  ,x  ,x  ,x  , //  setlocal..... utf8.... find....
  x  ,x  ,x  ,16 ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,107,x  ,x  ,51 , // ... rawlen........ popen.. gmatch
  64 ,x  ,x  ,x  ,x  ,56 ,x  ,x  ,x  ,x  ,x  ,x  ,136,x  ,x  ,90 , //  charpattern.... pack...... traceback.. mininteger
  x  ,x  ,x  ,x  ,x  ,86 ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,93 , // ..... log......... rad
  x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  , // ................
  x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,40 ,x  , // .............. loadlib.
  x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,18 ,43 ,x  ,x  , // ............ select searchers..
  x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,59 ,x  ,x  ,x  ,x  ,x  ,x  ,x  , // ........ reverse.......
  x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,117,39 , // .............. difftime loaded
  x  ,x  ,x  ,x  ,4  ,76 ,x  ,95 ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  , // .... dofile acos. randomseed........
  x  ,x  ,x  ,x  ,97 ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  , // .... sqrt...........
  x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,127,58 ,x  ,x  , // ............ getinfo rep..
  x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,35 ,x  ,x  ,x  ,x  ,0  , // .......... require.... _ENV
  27 ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,26 ,x  ,x  , //  close............ coroutine..
  23 ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,68 ,x  ,x  ,x  ,x  ,x  ,x  , //  _VERSION........ table......
  x  ,x  ,x  ,x  ,121,42 ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,15 ,x  , // .... rename preload........ rawget.
  x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x   // ................
  };
#undef x

#define Blthshshift(h) h >> 9
#define Hshseed   0x7748fa7c
#define Duncnt 26
#define Dun0hshmsk 31
#define Dun0hshbit  5

#define x D99_count

static const ub1 dun0hsh[32] = {
  x  ,x  ,x  ,x  ,x  ,11 ,5  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  ,x  , // ..... bnot pow.........
  x  ,x  ,x  ,x  ,3  ,10 ,x  ,x  ,20 ,8  ,25 ,x  ,15 ,9  ,x  ,x   // .... div bxor.. newindex band name. len bor..
  };
#undef x

#define Dun1hshmsk 31
#define Dun1hshbit  5

#define x D99_count

static const ub1 dun1hsh[32] = {
  x  ,x  ,24 ,2  ,0  ,1  ,x  ,7  ,12 ,x  ,x  ,14 ,x  ,19 ,x  ,4  , // .. mode mul add sub. idiv shl.. concat. index. mod
  13 ,x  ,x  ,x  ,x  ,21 ,x  ,x  ,x  ,x  ,23 ,x  ,x  ,6  ,x  ,x   //  shr.... call.... close.. unm..
  };
#undef x

#define Hshd0seed  0x0
#define Hshd1seed  0x4a57aec

#define Dn0hshshift(h) h >> 9
#define Dn1hshshift(h) h >> 15
static inline enum Token lookupkw2(ub1 c,ub1 d)
{
       if (c == 'd' && d == 'o') return Tdo;
  else if (c == 'i' && d == 'f') return Tif;
  else if (c == 'i' && d == 'n') return Tin;
  else return T99_count;
}

static const unsigned char kwhshlut[256] = {
    0,  2,  2,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  2,
    4,  0,  0,  0, 32, 17,  0,  0,  0,  0,  0,  0,  0,  0,128, 16,
    0,  0, 16, 16,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 24,  0,
   32,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0,  4,  0,  0,
    0,  0,  0,  0, 16,  0,  0,  0,  0,  0,  0, 36,  0,  0,  0,  0,
   32,  0,  0,  0, 64,  0,  0,  0,  0,162,  0,  0,  0,  0,  0,129,
    0,  0,  0,  0,  0,  0,128,  0,  0,  0, 32,  0,  0,  0, 72,  0,
    0,  0,  1,128,128,  0,128,  8,  0,  0,160,  0,  8, 64,  0,  0,
    0,  0,  0,  0, 32,  0, 96,  0,  0,  0,  0,  0,  0,  0,  0,  0,
    0,  0, 16,  0,  2, 32,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0,
   64, 64,  0, 16,  4,  0,  0,  4,  0,  0, 64,  0,  0,  0,  0,  0,
    0,  0,  0,  0,  0,  0,200,  0,  1,  0,  0,  0,  0,  1,  0,  0,
    0,  0,  4,  0,  2,  0,  0,  0,  0,  0,  0,  0, 66,  0,  4,  8,
    0,  0,  0,  0,  0,  0, 16,  0,  0,  0,  4,  0,  0,  0,  0, 16,
    0,128,  0,  0,  0, 64,  0,  0,  2,  0,  0,  0,  0,  1,  0,  0,
    0,  0,  0,  8,  0,  8,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0
}; // 32,36

static const unsigned char blthshlut[256] = {
   34, 34,  8,  4, 80,  0,  8,  0, 80, 44,212, 96, 96,132,  0,136,
   18, 10, 24,  1, 33, 65,162, 32, 48, 64,  8, 70, 16,  0,  1,111,
  192,  0,  0, 80,128,  0, 96,  0,145,  0, 10, 32,  2,  0,  8, 18,
  128, 16, 36,136, 35, 38, 13,  9, 10,  0,  8,  1, 36, 54, 32,  4,
   37, 16, 74, 40, 81, 20,199, 24, 28,  0,  4, 89,  0, 12, 97,128,
   67,  4, 32, 50, 67, 48,  0,156,  4, 64, 18, 32, 66, 36,198,128,
    1,  9,128, 32, 25, 68, 70, 74, 49,133,  2,226, 69, 66, 10,  3,
   48,162, 17,  0, 97,  2, 57,  2,  5, 32,  0, 20, 19,224,209, 10,
   25, 65,  8,221,  0, 68,185,  1, 16,128,200, 80,  8, 32,  6,  1,
    8, 33,  0,208,204, 20, 32,161, 65,  0,  0, 12,112, 76,192, 98,
   17, 64,132, 25,  4, 37,130,  3, 21,136, 32,  8, 88, 18,  8, 76,
  136,  8,196, 21,137, 18,  2, 64,136, 26, 65,128,145, 16,128,  5,
    1, 96,130, 24,162,  2, 51, 12,176, 45, 24, 16,134,  7, 11,  0,
  144,  1,144, 66,130, 40,208, 66,  1,168,129,  0,116, 12,  0, 84,
    0,  0, 43,  4, 20, 72, 65,  0,130, 32,132,128,242,160,  8, 34,
    0,128, 64,128, 23, 64,  0, 68,  8, 18,  8,161,  2, 66, 32, 17
}; // 172,172

static inline enum Bltin lookupblt2(ub1 c,ub1 d)
{
       if (c == '_' && d == 'G') return B_G;
  else if (c == 'p' && d == 'i') return Bpi;
  else if (c == 'i' && d == 'o') return Bio;
  else if (c == 'o' && d == 's') return Bos;
  else return B99_count;
}

static inline enum Dunder lookupdun2(ub1 c,ub1 d)
{
       if (c == 'e' && d == 'q') return Deq;
  else if (c == 'l' && d == 't') return Dlt;
  else if (c == 'l' && d == 'e') return Dle;
  else if (c == 'g' && d == 'c') return Dgc;
  else return D99_count;
}

/*
 UU  0   ' _'
 AF  1   ' ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz'
 N0  2   ' 0'
 NM  3   ' 123456789'
 HT  4   ' \t '
 VT  5   ' \f '
 CR  6   ' \r '
 NL  7   ' \n '
 HS  8   ' # '
 QQ  9   ' " ' '
 CO  10  ' { '
 RO  11  ' ( '
 SO  12  ' [ '
 CC  13  ' } '
 RC  14  ' ) '
 SC  15  ' ] '
 AO  16  ' < '
 AC  17  ' > '
 CL  18  ' : '
 SM  19  ' ; '
 CA  20  ' , '
 DT  21  ' . '
 EQ  22  ' = '
 PM  23  ' + - '
 O1  24  ' % & * / @ ^ | ~ '
 O2  25  ' ! '
 EOF 26  ' \0 '
 AN  1  + ' 0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ_abcdefghijklmnopqrstuvwxyz'
 NU  2  + ' 0123456789'
 HX  64 + ' ABCDEFabcdef'
 WS  0  - '   '
*/
#define x  27

static unsigned char ctab[256] = {
  26, x, x, x, x, x, x, x, x, 4, 7, x, 5, 6, x, x,  // 26, x, x, x, x, x, x, x, x,ht,nl, x,vt,cr, x, x,
   x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x,  //  x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x,
   x,25, 9, 8, x,24,24, 9,11,14,24,23,20,23,21,24,  //  x,o2,qq,hs, x,o1,o1,qq,ro,rc,o1,pm,ca,pm,dt,o1,
   2, 3, 3, 3, 3, 3, 3, 3, 3, 3,18,19,16,22,17, x,  // n0,nm,nm,nm,nm,nm,nm,nm,nm,nm,cl,sm,ao,eq,ac, x,
  24, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,  // o1,af,af,af,af,af,af,af,af,af,af,af,af,af,af,af,
   1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,12, x,15,24, 0,  // af,af,af,af,af,af,af,af,af,af,af,so, x,sc,o1,uu,
   x, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,  //  x,af,af,af,af,af,af,af,af,af,af,af,af,af,af,af,
   1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,10,24,13,24, x,  // af,af,af,af,af,af,af,af,af,af,af,co,o1,cc,o1, x,
   x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x,  //  x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x,
   x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x,  //  x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x,
   x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x,  //  x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x,
   x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x,  //  x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x,
   1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,  // af,af,af,af,af,af,af,af,af,af,af,af,af,af,af,af,
   1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,  // af,af,af,af,af,af,af,af,af,af,af,af,af,af,af,af,
   1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,  // af,af,af,af,af,af,af,af,af,af,af,af,af,af,af,af,
   1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, x, x
};
#undef x

static unsigned char utab[256] = {
  0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,
  0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,
  0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,
  3  ,3  ,3  ,3  ,3  ,3  ,3  ,3  ,3  ,3  ,0  ,0  ,0  ,0  ,0  ,0  ,
  0  ,65 ,65 ,65 ,65 ,65 ,65 ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,
  1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,0  ,0  ,0  ,0  ,1  ,
  0  ,65 ,65 ,65 ,65 ,65 ,65 ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,
  1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,0  ,0  ,0  ,0  ,0  ,
  1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,
  1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,
  1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,
  1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,
  1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,
  1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,
  1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,
  1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,0  ,0  
};

