/* syndef.h - parser defines

   generated by gensyn 0.1.0-alpha  3 Oct 2022  5:14  @nodiff

   from grammar lua.syn version 0.1.0 27 Sep 2022  9:53 lang lua @nodiff */

static char prodnampool[222] = 
  "stmt asgnst label goto do while repeat if forit stmt_9 mod blk_0 blk_1 dotlst namlst atrnamlst args_0 elsif field_0 field_1 fldlst expLst explst fncal_0 fncal_2 ndxpr tblexp ndxprx primex_0 grpexp fndef uexp_0 uexp_1 pexp ";

static const ub2 prodnampos[34] = { 0,5,12,18,23,26,32,39,42,48,55,59,65,71,78,85,95,102,108,116,124,131,138,145,153,161,167,174,181,190,197,203,210,217 };

enum Packed8 Production {
  Pstmt           =  0,Pasgnst         =  1,Plabel          =  2,Pgoto           =  3,
  Pdo             =  4,Pwhile          =  5,Prepeat         =  6,Pif             =  7,
  Pforit          =  8,Pstmt_9         =  9,Pmod            = 10,Pblk_0          = 11,
  Pblk_1          = 12,Pdotlst         = 13,Pnamlst         = 14,Patrnamlst      = 15,
  Pargs_0         = 16,Pelsif          = 17,Pfield_0        = 18,Pfield_1        = 19,
  Pfldlst         = 20,PexpLst         = 21,Pexplst         = 22,Pfncal_0        = 23,
  Pfncal_2        = 24,Pndxpr          = 25,Ptblexp         = 26,Pndxprx         = 27,
  Pprimex_0       = 28,Pgrpexp         = 29,Pfndef          = 30,Puexp_0         = 31,
  Puexp_1         = 32,Ppexp           = 33,Ptablen         = 34,Pctlxfer_stmt   = 34,Psepa_block     = 35,
  Pslit_args      = 36,Plaid           = 37,Pendrep         = 37,Pcount          = 38
};

